### PR TITLE
add my name to Qubes-corridor-Gateway

### PR DESCRIPTION
**Pull request by adrelanos**

### CODE REVIEW

**Comment by adrelanos** [comment]
https://github.com/QubesOS/qubes-issues/issues/2108

**Comment by andrewdavidwong** [comment]
Thanks, @adrelanos! Sorry for not having you listed there already!

**Comment by adrelanos** [comment]
Thanks! No problem! :)

**Comment by andrewdavidwong** [comment]
Just FYI, as a standard practice, I untrack issues when they are completed in order to keep the tracker uncluttered, so I just untracked #2108. However, your name is still of course associated with it in the commit history.

**Pull request merged**
